# Generated by Django 5.2 on 2025-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_ticketnumber_alter_ticket_assigneduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketAgentUID',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
